<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{4c5f8b35-f0df-4a6f-a8f4-070acba281dc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[Operation();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>